kind: pipeline
name: unittest

steps:
  - name: unittest
    image: golang:1.12-alpine
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - apk add --update git
      - go get -u ./...
      - go test -v ./...

---
kind: pipeline
name: build

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: clozed2u/example-cicd
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
